name: "Ubuntu nx log CI workflow"


on:
  push:
    branches: [ dev ]


jobs:

  ubuntu-latest-job:
    name: "nxlog ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch  
        neofetch   
    - name: "deploy nxlog"
      run: sudo make deploy-nxlog 
                         

  ubuntu-2004-job:
    name: "nxlog ubuntu  20.04"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch  
        neofetch   
    - name: "deploy nxlog"
      run: sudo make deploy-nxlog    
        


  ubuntu-1804-job:
    name: "nxlog ubuntu-18.04"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch  
        neofetch   
    - name: "deploy nxlog"
      run: sudo make deploy-nxlog 




